name: 'Tests: node.js: shimmed Promise'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '0.8 - 0.12'
      type: minors
      command: npm run test:promise-shimmed

  node:
    name: 'node, promise-shimmed tests'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
